language: node_js

node_js:
  - 8.4.0

cache:
  directories:
  - node_modules

script:
  - npm install
  - npm test
  - npm run test-scripts
  - npm run coverage

after_success:
- cat ./coverage/lcov.info | ./node_modules/.bin/codacy-coverage